import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const authHeader = req.headers.get('Authorization');
    if (!authHeader) {
      return new Response(JSON.stringify({ error: 'No authorization header' }), {
        status: 401,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    
    const userClient = createClient(supabaseUrl, Deno.env.get('SUPABASE_ANON_KEY')!, {
      global: { headers: { Authorization: authHeader } },
    });
    
    const { data: { user }, error: userError } = await userClient.auth.getUser();
    if (userError || !user) {
      return new Response(JSON.stringify({ error: 'Unauthorized' }), {
        status: 401,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    const serviceClient = createClient(supabaseUrl, supabaseServiceKey);

    const { amount, termWeeks } = await req.json();
    
    if (!amount || !termWeeks) {
      return new Response(JSON.stringify({ error: 'Amount and term required' }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    const purchaseAmount = parseFloat(amount);
    if (isNaN(purchaseAmount) || purchaseAmount < 10) {
      return new Response(JSON.stringify({ error: 'Minimum bond purchase is M$10' }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    // Valid terms
    const validTerms = [4, 13, 26, 52];
    if (!validTerms.includes(termWeeks)) {
      return new Response(JSON.stringify({ error: 'Invalid term' }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    // Get bond rate
    const { data: rateData } = await serviceClient
      .from('bond_rates')
      .select('*')
      .eq('term_weeks', termWeeks)
      .order('effective_date', { ascending: false })
      .limit(1)
      .maybeSingle();

    const annualYield = rateData?.annual_yield || 6.0;
    const monthlyYield = rateData?.monthly_yield || 0.5;

    // Calculate monthly interest and validate minimum M$10/month
    const monthlyInterest = purchaseAmount * (annualYield / 100) / 12;
    if (monthlyInterest < 10) {
      const minimumAmount = Math.ceil((10 * 12 * 100) / annualYield);
      return new Response(JSON.stringify({ 
        error: `Minimum investment is M$${minimumAmount} at ${annualYield}% APY to ensure M$10 monthly interest payment` 
      }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    // Get user balance
    const { data: balanceData } = await serviceClient
      .from('user_balances')
      .select('balance')
      .eq('user_id', user.id)
      .single();

    const currentBalance = balanceData?.balance || 0;

    if (purchaseAmount > currentBalance) {
      return new Response(JSON.stringify({ error: 'Insufficient balance' }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    // Calculate maturity and total return
    const now = new Date();
    const maturityDate = new Date(now);
    maturityDate.setDate(maturityDate.getDate() + (termWeeks * 7));
    
    // Next interest payment is 1 month from now
    const nextInterestDate = new Date(now);
    nextInterestDate.setMonth(nextInterestDate.getMonth() + 1);
    
    // Calculate total interest over the term (interest paid monthly, principal at end)
    const termMonths = termWeeks / 4; // Approximate months
    const totalInterest = monthlyInterest * termMonths;
    const totalReturn = purchaseAmount + totalInterest; // Principal + all interest

    // Deduct balance
    const { error: balanceError } = await serviceClient.rpc('modify_user_balance', {
      p_user_id: user.id,
      p_amount: purchaseAmount,
      p_operation: 'subtract'
    });

    if (balanceError) {
      console.error('Balance error:', balanceError);
      return new Response(JSON.stringify({ error: 'Failed to deduct balance' }), {
        status: 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    // Create bond (bond_code is auto-generated by trigger)
    const { data: bond, error: bondError } = await serviceClient.from('bonds').insert({
      user_id: user.id,
      amount: purchaseAmount,
      term_weeks: termWeeks,
      annual_yield: annualYield,
      monthly_yield: monthlyYield,
      maturity_date: maturityDate.toISOString(),
      next_interest_date: nextInterestDate.toISOString(),
      total_return: totalReturn,
    }).select().single();

    if (bondError) {
      // Refund on error
      await serviceClient.rpc('modify_user_balance', {
        p_user_id: user.id,
        p_amount: purchaseAmount,
        p_operation: 'add'
      });
      throw bondError;
    }

    // Record transaction
    const termLabels: Record<number, string> = {
      4: '4 Week T-Bill',
      13: '3 Month T-Bill',
      26: '6 Month T-Bill',
      52: '1 Year T-Bill',
    };

    await serviceClient.from('transactions').insert({
      user_id: user.id,
      type: 'bond_purchase',
      amount: -purchaseAmount,
      description: `Purchased ${termLabels[termWeeks]} (${bond.bond_code})`,
    });

    console.log(`User ${user.id} purchased ${termLabels[termWeeks]} (${bond.bond_code}) for M$${purchaseAmount}. Monthly interest: M$${monthlyInterest.toFixed(2)}`);

    return new Response(JSON.stringify({ 
      success: true, 
      bond,
      bondCode: bond.bond_code,
      monthlyInterest: monthlyInterest,
      totalReturn,
      maturityDate: maturityDate.toISOString(),
      nextInterestDate: nextInterestDate.toISOString(),
      message: `Purchased M$${purchaseAmount} ${termLabels[termWeeks]} (${bond.bond_code}). Monthly interest: M$${monthlyInterest.toFixed(2)}. Principal returned at maturity.`
    }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });

  } catch (error) {
    console.error('Bond purchase error:', error);
    return new Response(JSON.stringify({ error: error instanceof Error ? error.message : 'Purchase failed' }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});
